#!/bin/bash
echo 'Introducza la maquina, opciones: anoni, mac'
read maquina
NP=1

ficheroedp=mesh

nameedp="$ficheroedp.edp"
verbosity=0

case $maquina in
mac)
	rm ./freefem++.pref
	ff-mpirun -np $NP ./$nameedp -glut ffglut
	;;
maca)
	cp ../auxiliary/pref/freefem++maca.pref ./freefem++.pref
	dirseq=$HOME/FreeFem-sources/src/nw
	dirmpi=$HOME/FreeFem-sources/src/mpi
	mpirun -oversubscribe -np $NP $dirmpi/FreeFem++-mpi -v $verbosity ./$nameedp -glut $dirseq/ffglut
	;;
esac
