#!/bin/bash
maquina=mac
NP=2
# echo 'Programa: '
# read ficheroedp
ficheroedp=EF
echo 'Caso: '
read caso

nameedp="$ficheroedp.edp"
verbosity=0

case $maquina in
anoni)
	rm freefem++.pref 
	dirmpi=$HOME/ff++4.8/bin
    mpirun -oversubscribe -np $NP $dirmpi/FreeFem++-mpi -v $verbosity ./$nameedp > terminal.txt &
	;;
mac)
	cp ../auxiliary/pref/freefem++mac.pref ./freefem++.pref
	dirseq=$HOME/FreeFem-sources/src/nw
	dirmpi=$HOME/FreeFem-sources/src/mpi
	mpirun -oversubscribe -np $NP $dirmpi/FreeFem++-mpi -v $verbosity ./$nameedp -case $caso -glut $dirseq/ffglut
	;;
maca)
	cp ../auxiliary/pref/freefem++maca.pref ./freefem++.pref
	dirseq=$HOME/FreeFem-sources/src/nw
	dirmpi=$HOME/FreeFem-sources/src/mpi
	mpirun -oversubscribe -np $NP $dirmpi/FreeFem++-mpi -v $verbosity ./$nameedp -glut $dirseq/ffglut
	;;
esac
