#!/bin/bash
cp ../auxiliary/parameters.txt  parametersNN32NS.txt
cp ../auxiliary/parameters.txt  parametersNN32Smago.txt
cp ../auxiliary/parameters.txt  parametersNN64NS.txt
cp ../auxiliary/parameters.txt  parametersNN64Smago.txt
cp ../auxiliary/parameters.txt  parametersNN128NS.txt
cp ../auxiliary/parameters.txt  parametersNN128Smago.txt
cp ../auxiliary/parameters.txt  parametersNN256NS.txt
cp ../auxiliary/parameters.txt  parametersNN256Smago.txt
cp ../auxiliary/parameters.txt  parametersNN512NS.txt
cp ../auxiliary/parameters.txt  parametersNN512Smago.txt
cp ../auxiliary/parameters.txt  parametersNN32Stokes.txt