function createfigure(X1, YMatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 05-Aug-2020 14:30:10

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog(X1,YMatrix1,'LineWidth',1.5);

% Create xlabel
xlabel('k');

% Create ylabel
ylabel('E(k)');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log','YMinorTick','on','YScale','log');
