#!/bin/bash
echo 'Introducza la maquina, opciones: anoni, mac'
read maquina
echo 'Numero de procesadores:'
read NP
echo 'Caso:'
read caso
ficheroedp=offline

nameedp="$ficheroedp.edp"
verbosity=0

case $maquina in
anoni)
	rm freefem++.pref 
	dirmpi=$HOME/ff++4.8/bin
    mpirun -oversubscribe -np $NP $dirmpi/FreeFem++-mpi -v $verbosity ./$nameedp > terminal.txt &
	;;
mac)
	rm freefem++.pref
	ff-mpirun -np $NP ./$nameedp -case $caso -glut ffglut
#mpirun -oversubscribe -np $NP $dirmpi/FreeFem++-mpi -v $verbosity ./$nameedp -case $caso -glut $dirseq/ffglut
	;;
maca)
	cp ../auxiliary/pref/freefem++maca.pref ./freefem++.pref
	dirseq=$HOME/FreeFem-sources/src/nw
	dirmpi=$HOME/FreeFem-sources/src/mpi
	mpirun -oversubscribe -np $NP $dirmpi/FreeFem++-mpi -v $verbosity ./$nameedp -glut $dirseq/ffglut
	;;
esac
