#!/bin/bash
rm ../solutionsEulerExp/txt/*.txt
rm ../EIM/results/*.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN32NS.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN32Smago.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN64NS.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN64Smago.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN128NS.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN128Smago.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN256NS.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN256Smago.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN512NS.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN512Smago.txt
cp ../auxiliary/parameters.txt  ../solutionsEulerExp/parametersNN32Stokes.txt