function createfigure(X1, YMatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 17-Feb-2022 15:26:14

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'LineWidth',1.5);
set(loglog1(1),'DisplayName','k^{-1.6667}',...
    'Color',[0.87058824300766 0.490196079015732 0]);
set(loglog1(2),'Color',[0 0.447058826684952 0.74117648601532]);

% Create xlabel
xlabel('k');

% Create ylabel
ylabel('E(k)');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log','YMinorTick','on','YScale','log');
% Create legend
legend(axes1,'show');

